/*
 * This source file was generated by the Gradle 'init' task
 */
package aoc2024

import kotlin.math.abs

fun main() {
    val exampleInput = """
3   4
4   3
2   5
1   3
3   9
3   3
"""
    var indexOneList = mutableListOf<Int>()
    var indexTwoList = mutableListOf<Int>()

    "/day1".readFileText().lines().filter { it.isNotBlank() }.forEach {
        val (hello, hello2) = it.split("   ").map { it.toInt() }
        indexOneList.add(hello)
        indexTwoList.add(hello2)
    }

    indexOneList.sort()
    indexTwoList.sort()

    val distanceList = indexOneList.mapIndexed { index, indexOneItem ->
       abs(indexOneItem - indexTwoList[index])
    }
    println("$distanceList ${distanceList.sum()}")
}
