/*
 * This source file was generated by the Gradle 'init' task
 */
package aoc2024

import kotlin.math.abs

fun main() {
    val exampleInput = """
7 6 4 2 1
1 2 7 8 9
9 7 6 2 1
1 3 2 4 5
8 6 4 4 1
1 3 6 7 9
"""
    val reports = "/day2".readFileText().lines().filter { it.isNotBlank() }.map {
        it.split(" ").map { stringNumber -> stringNumber.toInt() }
    }
    val safeReports = reports.mapNotNull { report ->
        var increasing: Boolean? = null
        val (first, second) = report
        increasing = increaseValue(first, second)
        val isSafe = (1..<report.size).all { index ->
            val primary = report[index]
            val secondary = report[index - 1]
            abs(primary - secondary) <= 3 && increasing == increaseValue(secondary, primary)
        }
        if (isSafe) report else null
    }

    println("${safeReports.count()}")
}

fun increaseValue(first: Int, second: Int): Boolean? {
    return if (first > second) true else if(second > first) false else null
}

fun main22() {
}
