/*
 * This source file was generated by the Gradle 'init' task
 */
package aoc2024

fun main() {
    val exampleInput = """
        xmul(2,4)%&mul[3,7]!@^do_not_mul(5,5)+mul(32,64]then(mul(11,8)mul(8,5))
"""
    val input = "/day3".readFileText()
    val pattern = Regex("mul\\(\\d+,\\d+\\)")
    val digitPattern = Regex("\\d+")

    val sum = pattern.findAll(input).sumOf {
        digitPattern.findAll(it.value).map { it ->
            it.value.toInt()
        }.reduce{ acc, item -> acc * item }
    }
    println("sum: $sum")
}